rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
owl: <http://www.w3.org/2002/07/owl#>
xsd: <http://www.w3.org/2001/XMLSchema#>
dct: <http://purl.org/dc/terms/>
obo: <http://purl.obolibrary.org/obo/>
ensembl: <http://rdf.ebi.ac.uk/resource/ensembl/>
gxaterms: <http://rdf.ebi.ac.uk/terms/expressionatlas/>
gxa:  <http://rdf.ebi.ac.uk/resource/expressionatlas/>
foaf: <http://xmlns.com/foaf/0.1/>
