title: ChEMBL RDF
website: https://www.ebi.ac.uk/chembl/
description: ChEMBL is a manually curated database of bioactive molecules with drug-like properties.
tags: [ Drug/Chemical ]
provider: European Bioinformatics Institute
creators:
  - name: European Bioinformatics Institute
version: 32.0
issued: 2023-03-01
licenses:
  - Creative Commons Attribution-Share Alike 3.0 Unported License
