- Class obo:MP_0000026:
  - a: owl:Class
  - oboinowl:id:
    - id: "MP:0000026"
  - rdfs:label:
    - label: "abnormal inner ear morphology"
  - metadata:treeView*:
    - tree_view: Class
  - obo:IAO_0000115:  # definition
    - definition: "any structural anomaly of any components of the labyrinth, including the semicircular canals, vestibule and cochlea"
  - oboinowl:hasDbXref*:  # database_cross_reference
    - database_cross_reference: "GO:0042472"
  - oboinowl:hasExactSynonym*:  # has_exact_synonym
    - has_exact_synonym: "inner ear dysplasia"
  - oboinowl:hasOBONamespace:  # has_obo_namespace
    - has_obo_namespace: "MPheno.ontology"
  - rdfs:subClassOf*:
    - subclass_of: Class
  - skos:notation:
    - notation: "MP:0000026"
  - obo:IAO_0000231*:  # has obsolescence reason
    - has_obsolescence_reason: obo:IAO_0000227
  - obo:IAO_0100001*:  # term replaced by
    - term_replaced_by: Class
  - dc:contributor*:
    - contributor: <https://orcid.org/0000-0002-6490-7723>
  - dc:creator*:
    - creator: <https://orcid.org/0000-0002-6490-7723>
  - dc:date*:
    - date: 2017-05-22T15:58:02Z
  - dcterms:contributor*:
    - terms_contributor: <https://orcid.org/0000-0003-3691-0324>
  - oboinowl:consider*:
    - consider: "MP:0001312"
  - oboinowl:created_by*:
    - created_by: "csmith"
  - oboinowl:creation_date?:
    - creation_date: "2010-07-05T10:00:46Z"
  - oboinowl:hasAlternativeId*:
    - has_alternative_id: "MP:0000014"
  - oboinowl:hasBroadSynonym*:
    - has_broad_synonym: "auditory abnormalities"
  - oboinowl:hasNarrowSynonym*:
    - has_narrow_synonym: "abnormal ear development/ ear malformation"
  - oboinowl:hasRelatedSynonym*:
    - has_related_synonym: "abnormal eardrum morphology"
  - oboinowl:inSubset*:
    - in_subset: obo:mp#CvDC_Terms
  - rdfs:comment?:
    - comment: "Heart rate variability (HRV) is the variation of beat-to-beat intervals. ..."
  - owl:deprecated?:
    - deprecated: 1
