rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
obo: <http://purl.obolibrary.org/obo/>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
oboinowl: <http://www.geneontology.org/formats/oboInOwl#>
owl: <http://www.w3.org/2002/07/owl#>
skos: <http://www.w3.org/2004/02/skos/core#>
dc: <http://purl.org/dc/elements/1.1/>
dcterms: <http://purl.org/dc/terms/>
metadata: <http://data.bioontology.org/metadata/>
