nxp: <http://nextprot.org/rdf#>
nxp_annotation: <http://nextprot.org/rdf/annotation/>
nxp_db: <http://nextprot.org/rdf/db/>
nxp_entry: <http://nextprot.org/rdf/entry/>
nxp_gene: <http://nextprot.org/rdf/gene/>
nxp_iso: <http://nextprot.org/rdf/isoform/>
nxp_pub: <http://nextprot.org/rdf/publication/>
nxp_term: <http://nextprot.org/rdf/terminology/>
npx_evidence: <http://nextprot.org/rdf/evidence/>
npx_source: <http://nextprot.org/rdf/source/>
uniprot: <http://purl.uniprot.org/uniprot/>
up_page: <http://www.uniprot.org/uniprot/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
owl: <http://www.w3.org/2002/07/owl#>
skos: <http://www.w3.org/2004/02/skos/core#>