title: KNApSAcK RDF
website:
  - https://ddbj.nig.ac.jp/public/rdf/metabobank/knapsack/
  - http://www.knapsackfamily.com
description: RDFized dataset in the KNApSAcK family database.
tags: [ Compound, Taxonomy, Publication, Activity ]
provider: National Institute of Genetics
creators:
  - name: Takatomo Fujisawa
    affiliation: National Institute of Genetics (NIG)
  - nama: Tatsuya Kushida
    affiliation: RIKEN BioResource Research Center 
  - name: Yasunori Yamamoto
    affiliation: Database Center for Life Science (DBCLS)
  - name: Toshiaki Tokimatsu
    affiliation: National Institute of Genetics (NIG)
  - name: Issaku Yamada
    affiliation: The Noguchi Institute
  - name: Hideki Hatanaka
    affiliation: Database Center for Life Science (DBCLS)
  - name: Aki Hirai-Morita
    affiliation: Nara Institute of Science and Technology (NAIST)     
  - name: Shigehiko Kanaya
    affiliation: Nara Institute of Science and Technology (NAIST)     
  - name: Masanori Arita
    affiliation: National Institute of Genetics (NIG)
version: 0.2.0
issued: 2022-05-30
licenses:
  - Attribution 4.0 International (CC BY 4.0) 