title: KNApSAcK RDF
website:
  - https://ddbj.nig.ac.jp/public/rdf/metabobank/knapsack/
  - http://www.knapsackfamily.com
description: KNApSAcKファミリーデータベースのRDFデータセット
tags: [ Compound, Taxonomy, Publication, Activity ]
provider: 国立遺伝学研究所
creators:
  - name: 藤澤　貴智
    affiliation: 国立遺伝学研究所
  - nama: 櫛田　達矢
    affiliation: 国立研究開発法人理化学研究所 バイオリソース研究センター 
  - name: 山本　泰智
    affiliation: ライフサイエンス統合データベースセンター
  - name: 時松　敏明
    affiliation: 国立遺伝学研究所
  - name: 山田　一作
    affiliation: 野口研究所
  - name: 畠中　秀樹
    affiliation: ライフサイエンス統合データベースセンター
  - name: 森田（平井）晶
    affiliation: 奈良先端科学技術大学院大学
  - name: 金谷　重彦
    affiliation: 奈良先端科学技術大学院大学     
  - name: 有田　正規
    affiliation: 国立遺伝学研究所
version: 0.2.0
issued: 2022-05-30
licenses:
  - Attribution 4.0 International (CC BY 4.0) 