title: Rhea
website: https://www.rhea-db.org/
description: An expert curated resource of biochemical reactions designed for the annotation of enzymes and genome-scale metabolic networks and models. 
tags: [Protein Enzyme]
provider: SIB and EMBL-EBI
creators:
  - name: Anne Morgat
    affiliation: Swiss-Prot Group, SIB Swiss Institute of Bioinformatics
    affiliation: INRIA Grenoble Rhˆone-Alpes
  - name: Thierry Lombardot
    affiliation: Swiss-Prot Group, SIB Swiss Institute of Bioinformatics
  - name: Kristian B. Axelsen
    affiliation: Swiss-Prot Group, SIB Swiss Institute of Bioinformatics
  - name: Lucila Aimo
    affiliation: Swiss-Prot Group, SIB Swiss Institute of Bioinformatics
  - name: Anne Niknejad
    affiliation: Vital-IT, SIB Swiss Institute of Bioinformatics
  - name: Nevila Hyka-Nouspikel
    affiliation: Swiss-Prot Group, SIB Swiss Institute of Bioinformatics
  - name: Elisabeth Coudert
    affiliation: Swiss-Prot Group, SIB Swiss Institute of Bioinformatics
  - name: Monica Pozzato
    affiliation: Swiss-Prot Group, SIB Swiss Institute of Bioinformatics
  - name: Marco Pagni
    affiliation: Vital-IT, SIB Swiss Institute of Bioinformatics
  - name: Sébastien Moretti
    affiliation: Vital-IT, SIB Swiss Institute of Bioinformatics
    affiliation: Department of Ecology and Evolution, Biophore, Evolutionary Bioinformatics group,University of Lausanne
  - name: Steven Rosanoff
    affiliation: European Molecular Biology Laboratory, EuropeanBioinformatics Institute (EMBL-EBI)
  - name: Joseph Onwubiko
    affiliation: European Molecular Biology Laboratory, EuropeanBioinformatics Institute (EMBL-EBI)
  - name: Lydie Bougueleret
    affiliation: Swiss-Prot Group, SIB Swiss Institute of Bioinformatics
  - name: Ioannis Xenarios
    affiliation: Swiss-Prot Group, SIB Swiss Institute of Bioinformatics
    affiliation: Vital-IT, SIB Swiss Institute of Bioinformatics
    affiliation: University of Geneva, Department of Biochemistr
  - name: Nicole Redaschi
    affiliation: Swiss-Prot Group, SIB Swiss Institute of Bioinformatics
  - name: Alan Bridge
    affiliation: Swiss-Prot Group, SIB Swiss Institute of Bioinformatics
version: Rhea release 114
issued: 2020-08-13
licenses:
  - Attribution 4.0 International (CC BY 4.0) 
