rdfs: <http://www.w3.org/2000/01/rdf-schema#>
dct: <http://purl.org/dc/terms/>
obo: <http://purl.obolibrary.org/obo/>
sio: <http://semanticscience.org/resource/>
homologene: <http://identifiers.org/homologene/>
taxonomy: <http://identifiers.org/taxonomy/>
ncbigene: <http://identifiers.org/ncbigene/>
ncbiprotein: <http://identifiers.org/ncbiprotein/>
taxon: <http://ddbj.nig.ac.jp/ontologies/taxonomy/>
orth: <http://purl.org/net/orth#>
