insdc_ontology: <http://ddbj.nig.ac.jp/ontologies/nucleotide/>
insdcdiv: <http://ddbj.nig.ac.jp/ontologies/nucleotide/Division#>
insdc: <http://identifiers.org/insdc/>
bioproject: <http://identifiers.org/bioproject/>
biosample: <http://identifiers.org/biosample/>
entry: <http://identifiers.org/insdc/AP014957.1#>
insdcref: <http://ddbj.nig.ac.jp/ontologies/nucleotide/reference#>
pubmed: <http://identifiers.org/pubmed/>
region: <http://identifiers.org/insdc/AP014957.1#region:>
feature: <http://identifiers.org/insdc/AP014957.1#feature:>
taxonomy: <http://identifiers.org/taxonomy/>
ena: <http://www.ebi.ac.uk/ena/data/view/>
ddbj: <http://getentry.ddbj.nig.ac.jp/getentry/na/>
genbank: <http://www.ncbi.nlm.nih.gov/nuccore/>
faldo: <http://biohackathon.org/resource/faldo#>
position: <http://identifiers.org/insdc/AP014957.1#position:>
obo: <http://purl.obolibrary.org/obo/>
sio: <http://semanticscience.org/resource/>
dc: <http://purl.org/dc/elements/1.1/>
skos: <http://www.w3.org/2004/02/skos/core#>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
