title: UniProt RDF
website: https://uniprot.org/
description: The Universal Protein Resource (UniProt) is a comprehensive resource for protein sequence and annotation data.
tags: [ Protein ]
provider: The Swiss Institute of Bioinformatics
creators:
  - name: The Swiss Institute of Bioinformatics
version: 2023_01
issued: 2023-03-01
licenses:
  - Creative Commons Attribution 4.0 International (CC BY 4.0) License