title: FAMSBASE GPCR
website: 
description: RDFized reference gene expresson dataset derived from CAGE and GeneChip experiments in the RefEx database.
tags: [ Protein, Structure ]
provider:
creators:
  - name: Mitsuo Iwadate
    affiliation: Chuo University
  - name: Shuichi Kawahsima
    affiliation: Database Center for Life Science
  - name: 
    affiliation: 
version: 2016-03-24
issued: 2016-03-24
licenses:
  - Attribution 4.0 International (CC BY 4.0) Database Center for Life Science
