rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
owl: <http://www.w3.org/2002/07/owl#>
xsd: <http://www.w3.org/2001/XMLSchema#>
dct: <http://purl.org/dc/terms/>
obo: <http://purl.obolibrary.org/obo/>
fams: <http://purl.jp/bio/01/famsbase/>
famso: <http://purl.jp/bio/01/famsbase/ontology/>
edam: <http://edamontology.org/>
refseq: <http://identifiers.org/refseq/>
up: <http://identifiers.org/uniprot/>
faldo: <http://biohackathon.org/resource/faldo#>
pdb: <http://identifiers.org/pdb/>
