title: dbVar 
website: https://www.ncbi.nlm.nih.gov/dbvar/ 
description: dbVar is NCBI's database of human genomic Structural Variation — large variants >50 bp including insertions, deletions, duplications, inversions, mobile elements, translocations, and complex variants 
tags: ['structural variant']
provider: National Center for Biotechnology Information 
creators:
  - name: Med2RDF project   
    affiliation:  http://med2rdf.org/
licenses:
  -  https://www.ncbi.nlm.nih.gov/home/about/policies/
