dcterms: <http://purl.org/dc/terms/>
obo: <http://purl.obolibrary.org/obo/>
pint: <http://purl.jp/10/pint/>
xsd: <http://www.w3.org/2001/XMLSchema#>
ins: <http://purl.jp/10/instruct/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
uni: <http://identifiers.org/uniprot/>
pfm: <http://identifiers.org/Pfam/>
bp3: <http://www.biopax.org/release/biopax-level3.owl#>
