rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
dct: <http://purl.org/dc/terms/>
idorg_sra: <http://identifiers.org/insdc.sra/>
dra_ont: <http://ddbj.nig.ac.jp/ontologies/dra/>
