title: Ensembl RDF
website: https://www.ensembl.org
description: Ensembl is a collection of automatically annotated genome databases for vertebrates and a number of eukaryotes, integrated with all other relevant biological data available.
tags: [Gene, Protein]
provider: EMBL-EBI
creators:
  - name: Shuya Ikeda
    affiliation: Database Center for Life Science
version: 111
issued: 2024-01
licenses:
  - http://ensembl.org/info/about/legal/disclaimer.html
