title: Orthologous MAtrix (OMA) RDF
website: https://omabrowser.org
description: The OMA (Orthologous MAtrix) project is a method and database for the inference of orthologs among complete genomes. The OMA RDF is a view of the OMA database in RDF.
tags: [Genome, Gene, Phylogeny/Classification]
provider: SIB Swiss Institute of Bioinformatics
creators:
  - name: Adrian M. Altenhoff
    affiliation: SIB Swiss Institute of Bioinformatics
  - name: Christophe Dessimoz
    affiliation: SIB Swiss Institute of Bioinformatics
  - name: Tarcisio Mendes de Farias
    affiliation: SIB Swiss Institute of Bioinformatics
version: Jul2023
issued: 2023-07-01
licenses:
  - Creative Commons Attribution 4.0 International
