- ClusterOfOrthologs omahog:C0890540.1k.17n_33090 omahog:C0890540.1k.17n.32e.35b.28b.14b.9b.7c_3702:
  - a: orth:OrthologsCluster
  - dct:identifier:
    - cluster_id: "HOG:C0890540.1k.17n_33090"
  - orth:hasHomologousMember+:
    - cluster: ClusterOfOrthologs
    - member: Protein
  - orth:hasTaxonomicRange:
    - tax_range: tax:33090
  - orth:inDataset?:
    - dataset: omacurrent:DATASET_OMA

- Protein omainfo:ARATH11488:
  - a: orth:Protein
  - dct:identifier+:
    - protein_id: "AT2G07050"
  - rdfs:label:
    - protein_label: "CAS1"
  - rdfs:comment:
    - protein_comment: "transcript_id=AT2G07050.2"
  - orth:organism:
    - organism: Organism
  - sio:SIO_010079:
    - gene: oma:GENE_815275
  - obo:RO_0001018:
    - database: oma:ArabidopsisthalianafromEnsemblPlants38
  - lscr:xrefNCBIRefSeq:
    - protein_refseq: protein:NP_001325220
  - lscr:xrefUniprot:
    - protein_uniprot: uniprot:A0A1P8B2H6

- Organism omagenome:3702:
  - a: orth:Organism
  - obo:RO_0002162:
    - tax_id: tax:3702
