dct: <http://purl.org/dc/terms/>
obo: <http://purl.obolibrary.org/obo/>
sio: <http://semanticscience.org/resource/>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
orth: <http://purl.org/net/orth#>
oma: <http://omabrowser.org/ontology/oma#>
omahog: <https://omabrowser.org/oma/hog/resolve/HOG:>
omainfo: <https://omabrowser.org/oma/info/>
omagenome: <https://omabrowser.org/oma/genome/>
omacurrent: <https://omabrowser.org/oma/current/#>
protein: <https://www.ncbi.nlm.nih.gov/protein/>
tax: <http://purl.uniprot.org/taxonomy/>
uniprot: <http://purl.uniprot.org/uniprot/>
lscr: <http://purl.org/lscr#>
