title: "jPOST databse RDF"
website: https://globe.jpostdb.org/
description: "jPOST database RDF is described the re-analyzed proteome dataset in the jPOST project."
tags: []
provider:
creators:
  - name: "Yuki Moriya"
    affiliation: "Database Center for Life Science"
version: 202006
issued: 2020-06-09
licenses:
  - "Attribution 4.0 International (CC BY 4.0)"
