gdgdb_schema: <http://jcggdb.jp/rdf/diseases/gdgdb-schema#>
ggdonto: <http://jcggdb.jp/rdf/diseases/ggdonto#>
ggdonto_schema: <http://jcggdb.jp/rdf/diseases/ggdonto-schema#>
gmncbi_schema: <http://jcggdb.jp/rdf/diseases/gmncbi-schema#>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
skos: <http://www.w3.org/2004/02/skos/core#>
dct: <http://purl.org/dc/terms/>
