sparql:
  description: Obrain drug-gene interaction pairs from DGIdb
  variables:
    - interaction_type
    - drug_name
    - chembl_molecule
    - gene_name
    - alternative_name
    - ncbi_gene
    - publication

stanza:
  description: Obrain drug-gene interaction pairs from DGIdb
  parameters:
    gene_name: ADH1A
  variables:
    - interaction_type
    - drug_name
    - chembl_molecule
    - gene_name
    - alternative_name
    - ncbi_gene
    - publication

togoid:
  description: Obtain pairs of ChEMBL and NCBI Gene for TogoID
  variables: [ chembl_molecule, ncbi_gene ]
