dgidb:
  output_dir: "stanza"
  label: "DGIdb"
  definition: "Stanza of drug-gene interaction"
  sparql: stanza
  parameters:
    gene_name:
      example: ADH1A
      description: Gene symbol
      required: true
