title: Reactome RDF
website: https://reactome.org/
description: REACTOME is an open-source, open access, manually curated and peer-reviewed pathway database.
tags: [Interaction/Pathway]
provider: Reactome Team (https://reactome.org/)
creators: Reactome Team (https://reactome.org/)
version: 84
issued: 2023-04
licenses:
  - Creative Commons Public Domain (CC0) License
