sparql:
  description: RDFized reference gene expresson dataset derived from CAGE and GeneChip experiments in the RefEx database.
  variables: [refex_id, ex_value, see_also, RefExSample, sample_id, taxonomy, age, stage, description, cell_type, disease, dev_site, refexo_sample]

stanza_sparql:
  description: RDFized reference gene expresson dataset derived from CAGE and GeneChip experiments in the RefEx database.
  variables: [refex_id, ex_value, see_also, RefExSample, sample_id, taxonomy, age, stage, description, cell_type, disease, dev_site, refexo_sample]
  parameters:
    refex_id: RFX0000113860
