- Naddentry nadd:monad0024:
  - a:
    - jst:Chemical
    - innovation:Innovation
  - obo:RO_0002606+:
    - disease: obo:MONDO_0005417, obo:MONDO_0005150
  - innovation:developedBy+:
    - company: "OSI Eyetech, Inc"
    - wikidata: wikidata:Q663596 # Gilead Sciences, Inc.
  - sio:SIO_000223+: # has property
    - type_so: obo:SO_0000031 # aptamer
    - type_ncit: ncit:C1749
  - sio:SIO_000362+: # satisfies
    - []:
      - a: ncit:C15206
      - sio:SIO_000008:
        - phase: ncit:C25425
      - sio:SIO_000066+:
        - provider: wikidata:Q183 , wikidata:Q30
  - sio:SIO_000671*: # has identifier
    - other_id: uatc:S01LA03, uatc:S01L, drugbank:DB05528
  - sio:SIO_010423+: # target
    - uniprot_id: uniprot:P15692 # uniprot:P15692
    - pdb_id: pdbr:3BDY
  - rdfs:comment:
    - comment: "Macugen is used for the treatment of angiogenic age-related macular degeneration (AMD)."
  - rdfs:label+:
    - product_name: '"Macugen"@en'
    - sequence: "((2'-deoxy-2'-fluoro)C-Gm-Gm-A-A-(2'-deoxy-2'-fluoro)U-(2'-deoxy-2'-fluoro)C-Am-Gm-(2'-deoxy-2'-fluoro)U-Gm-Am-Am-(2'-deoxy-2'-fluoro)U-Gm-(2'-deoxy-2'-fluoro)C-(2'-deoxy-2'-fluoro)U-(2'-deoxy-2'fluoro)U-Am-(2'-deoxy-2'-fluoro)U-Am-(2'-deoxy-2'-fluoro)C-Am-(2'-deoxy-2'-fluoro)U-(2'deoxy-2'-fluoro)C-(2'-deoxy-2'-fluoro)C-Gm-(3'→3')-dT), 5'-ester with α,α'-[4,12-dioxo-6[[[5-(phosphoonoxy)pentyl]amino] carbonyl]-3,13-dioxa-5,11-diaza-1,15pentadecanediyl]bis[ω-methoxypoly(oxy-1,2-ethanediyl)]"
  - rdfs:seeAlso+:
    - source: clinicaltrial:2007-006290-90/DE, clinicaltrial:2006-000722-31/DE, rxlist:macugen-drug.htm
  - skos:alternativeLabel*:
    - alt_product_name: '"Pegaptanib"@en'

