ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
uatc: <http://purl.bioontology.org/ontology/UATC/>
nadd: <http://purl.jp/bio/18/nadd/>
innovation: <http://purl.org/innovation/>
uniprot: <http://purl.uniprot.org/uniprot/>
jst: <http://vocab.jst.go.jp/terms/sti#>
wikidata: <https://identifiers.org/wikidata/>
pdbr: <https://rdf.wwpdb.org/pdb/>
clinicaltrial: <https://www.clinicaltrialsregister.eu/ctr-search/trial/>
obo: <http://purl.obolibrary.org/obo/>
sio: <http://semanticscience.org/resource/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
skos: <http://www.w3.org/2004/02/skos/core#>
drugbank: <http://bio2rdf.org/drugbank:>
rxlist: <http://www.rxlist.com/>
