hint_pair:
  output_dir: "stanza" # /path/to/output/dir
  label: "HiNT pair"
  definition: "Stanza of a protein-protein interaction pair"
  sparql: pair_stanza  # defined in sparql.yaml
  parameters:
    pair0:
      example: uni:A0A024QYV7
      description: UniProt identifier
      required: true
