rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
dct: <http://purl.org/dc/terms/>
foaf: <http://xmlns.com/foaf/0.1/>
obo: <http://purl.obolibrary.org/obo/>
sio: <http://semanticscience.org/resource/>
faldo: <http://biohackathon.org/resource/faldo#>
hco: <http://identifiers.org/hco/>
hgnc: <http://identifiers.org/hgnc/>
so: <http://purl.obolibrary.org/obo/so#>
refseq: <http://identifiers.org/refseq/>
dbsnp: <http://identifiers.org/dbsnp>
m2r: <http://med2rdf.org/ontology/med2rdf#>
ensembl: <http://identifiers.org/ensembl/>
exac: <http://identifiers.org/exac.variant/>
exo: <http://purl.jp/bio/10/exac/>
browser: <http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&highlight=hg19.>
hp: <http://exac.broadinstitute.org/variant/>
