annotations:
  description: Obrain variant annotations from ExAC
  subject: ExACValiation
  parameters:
    identifier: 4-100197800-C-T
  variables:
    - identifier
    - allele_count
    - allele_num
    - num_of_homozygotes
    - allele_frequency
    - consequence
    - hgvs
    - annotation_consequence
    - annotation_gene
    - annotation_protein
    - annotation_transcript
    - annotation_gene_symbol
    - annotation_agvsc
    - annotation_hgvsp
    - annotation_hgnc

populations:
  description: Obrain variant populations from ExAC
  subject: ExACValiation
  parameters:
    identifier: 4-100197800-C-T
  variables:
    - identifier
    - population_label
    - population_allele_count
    - population_allele_frequency
    - population_allele_num
    - population_num_of_homozygotes
