exac:
  output_dir: "stanza"
  label: "ExAC"
  definition: "Stanza of a variant populations"
  sparql: populations
  parameters:
    identifier:
      example: 4-100197800-C-T
      description: ExAC identifier
      required: true
