gene:
  description: Obrain variations on certain gene
  parameters:
    gene_label: "PAX4"
  variables:
    - gene_label
    - identifier
    - dbsnp
    - reference
    - position
    - reference_allele
    - alternative_allele
