sparql:
  description: Obrain IF_0
  variables: [ package_insert, drug_label ]

derivation:
  variables: [ InterviewForm, if_drug_name, derivation ]

kinki_sparql:
  description: Obtain data from section 8.2
  variables: [ InterviewForm, if_8_2_item, if_8_2_ref ] 

