# Cardinality is yet to be fixed.
- Class obo:UBERON_0002048:
  - a: owl:Class
  - oboinowl:id:
    - id: "UBERON:00002048"
  - rdfs:label:
    - label: "lung"
  - obo:IAO_0000115:  # definition
    - definition: "Respiration organ that develops as an outpocketing of the esophagus."
  - obo:IAO_0000116*:  # editor note
    - editor_note: "TODO - check frog/fish"
  - obo:IAO_0000232*:  # curator note
    - curator_note: "See notes for pars intermedia of adenohypophysis."
  - obo:IAO_0006012*:  # scheduled for obsoletion on or after
    - scheduled_for_obsoletion_on_or_after: "2023-04-20"
  - obo:IAO_0100001*:  # term replaced by
    - term_replaced_by: "UBERON:0002275"
  - obo:RO_0002161*:  # never_in_taxon
    - never_in_taxon: obo:NCBITaxon_32443
  - obo:RO_0002171*:  # mutually_spatially_disjoint_with
    - mutually_spatially_disjoint_with: Class
  - obo:RO_0002173*:  # ambiguous_for_taxon
    - ambiguous_for_taxon: obo:NCBITaxon_8782
  - obo:RO_0002174*:  # dubious_for_taxon
    - dubious_for_taxon: obo:NCBITaxon_10090
  - obo:RO_0002175*:  # present_in_taxon
    - present_in_taxon: obo:NCBITaxon_9606
  - obo:RO_0002475*:  # has_no_connections_with
    - has_no_connections_with: Class
  - obo:UBPROP_0000001*:  # external_definition
    - external_definition: "Dense regular connective tissue that connects muscle to bone.[VSAO]"
  - obo:UBPROP_0000002*:  # axiom_lost_from_external_ontology
    - axiom_lost_from_external_ontology: "relationship loss: overlaps hyomandibular-otic region joint (TAO:0001947)[TAO]"
  - obo:UBPROP_0000003*:  # homology_notes
    - homology_notes: "(...) an essentially similar sequence of events occurs during the embryonic development of the vertebrate eye. The eye initially develops as a single median evagination of the diencephalon that soon bifurcates to form the paired optic vesicles. As each optic vesicle grows towards the body surface, its proximal part narrows as the optic stalk, and its distal part invaginates to form a two-layered optic cup. (...) The outer layer of the optic cup becomes the pigment layer of the retina, whereas the inner layer differentiates into the photoreceptive cells and neuronal layers of the retina.[well established][VHOG]"
  - obo:UBPROP_0000004*:  # provenance_notes
    - provenance_notes: "This class was sourced from an external ontology (teleost_anatomy). Its definitions, naming conventions and relationships may need to be checked for compatibility with uberon"
  - obo:UBPROP_0000005*:  # external_comment
    - external_comment: "[In TAO], This term was made obsolete because it is considered a synonym of membrane bone (VSAO:0000023).[TAO]"
  - obo:UBPROP_0000006*:  # implements_design_pattern
    - implements_design_pattern: <https://github.com/obophenotype/uberon/wiki/Modeling-paired-structures-Design-Pattern>
  - obo:UBPROP_0000007*:  # has_relational_adjective
    - has_relational_adjective: "ventral"
  - obo:UBPROP_0000008*:  # taxon_notes
    - taxon_notes: "the basic trilaminar structure of the dentate gyrus is common across all species studied, with relatively minimal phylogenetic variation[PMC2492885]"
  - obo:UBPROP_0000009*:  # function_notes
    - function_notes: "vomiting center in humans"
  - obo:UBPROP_0000010*:  # structure_notes
    - structure_notes: "A secretion of the prostate this is slightly alkaline fluid, milky or white in appearance. Usually constitutes 20-30% of the volume of the semen along with spermatozoa and seminal vesicle fluid [Wikipedia:Prostate#Secretions]"
  - obo:UBPROP_0000011*:  # development_notes
    - development_notes: "contributes significantly in building up the GABAergic cortical cell population[WP]"
  - obo:UBPROP_0000012*:  # external_ontology_notes
    - external_ontology_notes: "this is a 'set of anatomical planes' in FMA"
  - obo:UBPROP_0000013*:  # terminology_notes
    - terminology_notes: "Gilbert uses visceral endoderm as a synonym for primitive endoderm/hypoblast"
  - obo:UBPROP_0000014*:  # actions_notes
    - actions_notes: "In some mammals these muscles can adjust the direction of the pinna. In humans these muscles possess very little action. The auricularis anterior draws the auricula forward and upward; the Auricularis superior slightly raises it; and the Auricularis posterior draws it backward."
  - obo:UBPROP_0000015*:  # location_notes
    - location_notes: "Bounded medially by the Lamina orbitalis of the Os ethmoidale and laterally by the Maxilla and Os palatinum and in the dog also by the Os lacrimale[NOMINA ANATOMICA VETERINARIA (2005)]"
  - obo:UBPROP_0000103*:  # pharyngeal arch number
    - pharyngeal_arch_number: 7
  - obo:UBPROP_0000104*:  # ray number
    - ray_number: 6
  - obo:UBPROP_0000105*:  # phalanx number
    - phalanx_number: 1
  - obo:UBPROP_0000106*:  # rib number
    - rib_number: 12
  - obo:UBPROP_0000107*:  # vertebra number
    - vertebra_number: 1
  - obo:UBPROP_0000108*:  # somite number
    - somite_number: 26
  - obo:UBPROP_0000111*:  # rhombomere number
    - rhombomere_number: 1
  - obo:UBPROP_0000112*:  # tooth number
    - tooth_number: 1
  - obo:UBPROP_0000201*:  # source atlas
    - source_atlas: obo:Harvard-Oxford_Atlas
  - obo:UBPROP_0000202*:  # fma_set_term
    - fma_set_term: obo:FMA_71364
  - dc:contributor*:
    - dc_contributor: <https://github.com/cerivs>
  - dcterms:contributor*:
    - dcterms_contributor: <https://orcid.org/0000-0001-9114-8737>
  - dcterms:date*:  # date
    - date: 2021-06-02T00:19:07Z
  - oboinowl:consider*:
    - consider: "BIRNLEX:1003"
  - oboinowl:created_by*:
    - created_by: <http://orcid.org/0000-0002-2825-0621>
  - oboinowl:creation_date*:
    - creation_date: 2009-07-30T07:57:38Z
  - oboinowl:hasAlternativeId*:
    - has_alternative_id: "UBERON:0003263"
  - oboinowl:hasBroadSynonym*:
    - has_broad_synonym: "reticular formation"
  - oboinowl:hasDbXref*:
    - database_cross_reference: "CALOHA:TS-1266"
  - oboinowl:hasExactSynonym*:
    - has_exact_synonym: "NA"
  - oboinowl:hasNarrowSynonym*:
    - has_narrow_synonym: "elastic fiber"
  - oboinowl:hasOBONamespace*:
    - has_obo_namespace: "uberon"
  - oboinowl:hasRelatedSynonym*:
    - has_related_synonym: "basal ganglia"
  - oboinowl:inSubset*:
    - in_subset: obo:uberon/core#early_development
  - rdfs:comment*:
    - comment: "Taxon notes:\" the ascidian tube-like heart lacks chambers....The ascidian heart is formed after metamorphosis as a simple tube-like structure with a single-layered myoepithelium that is continuous with a single-layered pericar- dial wall. It lacks chambers and endocardium.... The innovation of the chambered heart was a key event in vertebrate evolution, because the chambered heart generates one-way blood flow with high pressure, a critical requirement for the efficient blood supply of large-body vertebrates... all extant vertebrates have hearts with two or more chambers (Moorman and Christoffels 2003)\" DOI:10.1101/gad.1485706"
  - rdfs:seeAlso*:
    - see_also: <https://github.com/obophenotype/uberon/issues/336>
  - rdfs:subClassOf*:
    - subclass_of: Class
  - owl:deprecated*:
    - deprecated: 1
  - owl:disjointWith*:
    - disjoint_with: Class
  - owl:equivalentClass*:
    - equivalent_class: Class
  - foaf:depicted_by*:
    - depicted_by: <http://upload.wikimedia.org/wikipedia/commons/7/77/Gray709.png>
