dc: <http://purl.org/dc/elements/1.1/>
dcterms: <http://purl.org/dc/terms/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
owl: <http://www.w3.org/2002/07/owl#>
oboinowl: <http://www.geneontology.org/formats/oboInOwl#>
foaf: <http://xmlns.com/foaf/0.1/>
obo: <http://purl.obolibrary.org/obo/>
