title: RefEx RDF
website: http://refex.dbcls.jp/index.php?lang=ja
description: RDFized reference gene expresson dataset derived from CAGE and GeneChip experiments in the RefEx database.
tags: [ Gene, Tag sequence (nucleic acid), Gene expression ]
provider:
creators:
  - name: Shuichi Kawahsima
    affiliation: Database Center for Life Science
  - name: Hiromasa Ono
    affiliation: Database Center for Life Science
version: 2017-04-07
issued: 2017-04-07
licenses:
  - Attribution 4.0 International (CC BY 4.0) Database Center for Life Science
