dbsnp:
  output_dir: "stanza"
  label: "dbSNP"
  definition: "Stanza of a genetic variation"
  sparql: stanza
  parameters:
    identifier:
      example: rs1000017372
      description: dbSNP identifier
      required: true
