refex_entry:
  output_dir: "stanza" # /path/to/output/dir
  label: "RefEx entry"
  definition: "Stanza for RefEx entry"
  sparql: stanza_sparql  # defined in sparql.yaml
  parameters:
    refex_id:
      example: "RFX0000062273"
      description: RefEx identifier
      required: true
