rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
owl: <http://www.w3.org/2002/07/owl#>
xsd: <http://www.w3.org/2001/XMLSchema#>
dct: <http://purl.org/dc/terms/>
obo: <http://purl.obolibrary.org/obo/>
skos: <http://www.w3.org/2004/02/skos/core#>
foaf: <http://xmlns.com/foaf/0.1/>
faldo: <http://biohackathon.org/resource/faldo#> 
up: <http://purl.uniprot.org/uniprot/>
core: <http://purl.uniprot.org/core/>
taxonomy: <http://purl.uniprot.org/taxonomy/>
enzyme: <http://purl.uniprot.org/enzyme/>
citations: <http://purl.uniprot.org/citations/>
pubmed: <https://pubmed.ncbi.nlm.nih.gov/>
keywords: <http://purl.uniprot.org/keywords/>
isoforms: <http://purl.uniprot.org/isoforms/>
rhea: <http://rdf.rhea-db.org/>
dbsnp: <http://purl.uniprot.org/dbsnp/>
locations: <http://purl.uniprot.org/locations/>
annotation: <http://purl.uniprot.org/annotation/>
diseases: <http://purl.uniprot.org/diseases/>
pdbx: <http://rdf.wwpdb.org/schema/pdbx-v50.owl#>
chembl: <http://rdf.ebi.ac.uk/terms/chembl#>
idorg: <http://identifiers.org/>
database: <http://purl.uniprot.org/database/>
unipathway: <http://purl.uniprot.org/unipathway/>
pdb: <http://rdf.wwpdb.org/pdb/>
reactome: <http://identifiers.org/reactome/>
ncbigene: <http://identifiers.org/ncbigene/>
oma: <http://omabrowser.org/ontology/oma#>
bgee: <http://bgee.org/#>
orth: <http://purl.org/net/orth#>
genex: <http://purl.org/genex#>
lscr: <http://purl.org/lscr#>
ensg: <http://rdf.ebi.ac.uk/resource/ensembl/>
dcterms: <http://purl.org/dc/terms/>
efo: <http://www.ebi.ac.uk/efo/>