title: Dataset of NBRC bioresource
website: https://www.nite.go.jp/en/index.html
description: Dataset of NBRC bioresource is a dataset for microbes which are maintained, managed and provided from NBRC (NITE Biological Resource Center).
tags: [ Organism, Cell, Bioresource ]
provider: National Institute of Technology and Evaluation
creators:
  - name: Masami Namihira
    affiliation: National Institute of Technology and Evaluation
  - name: Yuko Kitahashi
    affiliation: National Institute of Technology and Evaluation
  - name: Natsuko Ichikawa
    affiliation: National Institute of Technology and Evaluation
version: release_20190823
issued: 2019-08-23
licenses:
  - Creative Commons Attribution-ShareAlike 2.1 Japan (CC BY-SA 2.1 JP)
  - Dataset of NBRC bioresource (C) NITE NBRC licensed under CC Attribution-ShareAlike 2.1 Japan
