sparql:
  description: Obtain taxonomy ID and preferred label of a bioresource 
  variables: [nbrc_id, clade, name, alias, taxid, attribute, habitat]
  parameters:
    nbrc_id: NBRC_00100650
    attribute: meo:MEO_0000198

stanza_sparql:
    description: NBRC bioresource is a dataset for microbes which are maintained, managed and provided from NBRC
    variables: [clade, name, alias, taxid, xref]
    parameters:
      nbrc_id: NBRC_00100650

test_sparql:
  variables: [ Culture, habitat, location ]
