db: <http://purl.jp/bio/03/dbcatalog/>
dcat: <http://www.w3.org/ns/dcat#>
dcterms: <http://purl.org/dc/terms/>
pubmed: <http://rdf.ncbi.nlm.nih.gov/pubmed/>
taxddbj: <http://ddbj.nig.ac.jp/ontologies/taxonomy/>
lang: <http://id.loc.gov/vocabulary/iso639-1/>
foaf: <http://xmlns.com/foaf/0.1/>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
schema: <http://schema.org/>
tag: <http://integbio.jp/dbcatalog/dbcatalogtag.owl#>
skos: <http://www.w3.org/2004/02/skos/core#>
xsd: <http://www.w3.org/2001/XMLSchema#>
owl: <http://www.w3.org/2002/07/owl#>
dc: <http://purl.org/dc/elements/1.1/>
pav: <http://purl.org/pav/>
bibo: <http://purl.org/ontology/bibo/>
prism: <http://prismstandard.org/namespaces/1.2/basic/>