title: Nikkaji RDF
website: http://dbarchive.biosciencedbc.jp/en/nikkaji/desc.html
description: NBDC NikkajiRDF is RDF data of Japan Chemical Substance Dictionary (Nikkaji), which is one of the largest chemical substance databases in Japan.
tags: [ Drug/Chemical, Others, Structure, Image/Movie]
provider: Japan Science and Technology Agency (JST)
creators: Japan Science and Technology Agency (JST)
version: 2017-01-12
issued: 2017-01-12
licenses:
  - Creative Commons Attribution 2.1 Japan (CC BY 2.1 JP)
  - NBDC NikkajiRDF © Japan Science and Technology Agency licensed under CC Attribution 2.1 Japan
