atlas: <http://www.ebi.ac.uk/gxa/query?conditionQuery=>
b2rdrugb: <http://bio2rdf.org/drugbank:DB>
b2rhmdb: <http://bio2rdf.org/hmdb:>
b2rkegg: <http://bio2rdf.org/kegg:>
b2rpcc: <http://bio2rdf.org/pubchem.compound:>
b2rpcs: <http://bio2rdf.org/pubchem.substance:>
b2rpkb: <http://bio2rdf.org/pharmgkb:>
bibo: <http://purl.org/ontology/bibo/>
chebi: <http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A>
chembl: <https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL>
cheminf: <http://semanticscience.org/resource/>
crossref: <http://example.org/test/crossref/>
dbpo: <http://dbpedia.org/ontology/>
dc: <http://purl.org/dc/elements/1.1/>
dcat: <http://www.w3.org/ns/dcat#>
dct: <http://purl.org/dc/terms/>
dcterms: <http://purl.org/dc/terms/>
drugb: <http://www.drugbank.ca/drugs/DB>
emol: <https://www.emolecules.com/cgi-bin/more?vid=>
fdasrs: <http://fdasis.nlm.nih.gov/srs/ProxyServlet?mergeData=true&objectHandle=DBMaint&APPLICATION_NAME=fdasrs&actionHandle=default&nextPage=jsp/srs/ResultScreen.jsp&TXTSUPERLISTID=>
foaf: <http://xmlns.com/foaf/0.1/>
glycan: <http://rdf.glycoinfo.org/glycan/>
gtopdb: <http://www.guidetopharmacology.org/GRAC/LigandDisplayForward?ligandId=>
hmdb: <http://www.hmdb.ca/metabolites/>
ibm: <http://www-935.ibm.com/services/us/gbs/bao/siip/nih/?sid=>
idchebi: <http://identifiers.org/chebi/CHEBI:>
idchembl: <http://identifiers.org/chembl.compound/CHEMBL>
iddrugb: <http://identifiers.org/drugbank/DB>
idhmdb: <http://identifiers.org/hmdb/>
idkeggc: <http://identifiers.org/kegg.compound/>
idpcc: <http://identifiers.org/pubchem.compound/>
idpcs: <http://identifiers.org/pubchem.substance/>
idpdb: <http://identifiers.org/pdb-ccd/>
idpkb: <http://identifiers.org/pharmgkb.drug/>
idzinc: <http://identifiers.org/zinc/>
inchi: <http://glyconavi.org/inchi/>
jglobal: <http://stirdf.jst.go.jp/id/>
jst: <http://vocab.jst.go.jp/terms/sti#>
jstd: <http://vocab.jst.go.jp/terms/vlist#>
jstpat: <http://vocab.jst.go.jp/terms/patent#>
keggbget: <http://www.genome.jp/dbget-bin/www_bget?>
ndl: <http://ndl.go.jp/dcndl/terms/>
nikkaji: <http://stirdf.jst.go.jp/cde/nikkaji/>
obo: <http://purl.obolibrary.org/obo/>
obochebi: <http://purl.obolibrary.org/obo/CHEBI_>
owl: <http://www.w3.org/2002/07/owl#>
pav: <http://purl.org/pav/>
pcc: <http://pubchem.ncbi.nlm.nih.gov/compound/>
pcdotf: <http://pubchem.ncbi.nlm.nih.gov/substance/>
pcs: <http://pubchem.ncbi.nlm.nih.gov/substance/>
pcscid: <http://pubchem.ncbi.nlm.nih.gov/summary/summary.cgi?cid=>
pcssid: <http://pubchem.ncbi.nlm.nih.gov/summary/summary.cgi?sid=>
pdbe: <http://www.ebi.ac.uk/pdbe-srv/pdbechem/chemicalCompound/show/>
pdbj: <http://pdbj.org/chemie/summary/>
pkb: <http://www.pharmgkb.org/drug/>
prism: <http://prismstandard.org/namespaces/basic/2.0/>
rchembl: <http://rdf.ebi.ac.uk/resource/chembl/molecule/CHEMBL>
rcsb: <http://ligand-expo.rcsb.org/pyapps/ldHandler.py?formid=cc-index-search&operation=ccid&target=>
rda: <http://rdvocab.info/ElementsGr2/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
rpccid: <http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID>
rpcsid: <http://rdf.ncbi.nlm.nih.gov/pubchem/substance/SID>
rpdb: <http://rdf.wwpdb.org/cc/>
schema: <http://schema.org/>
schembl: <https://www.surechembl.org/chemical/>
semanticscience: <http://semanticscience.org/resource/>
sio: <http://semanticscience.org/resource/>
skos: <http://www.w3.org/2004/02/skos/core#>
ssc: <http://semanticscience.org/resource/>
tl: <http://purl.org/NET/c4dm/timeline.owl#>
vcard: <http://www.w3.org/2006/vcard/ns#>
void: <http://rdfs.org/ns/void#>
xl: <http://www.w3.org/2008/05/skos-xl#>
xsd: <http://www.w3.org/2001/XMLSchema#>
zinc: <http://zinc.docking.org/substance/>
