nikkaji_entry:
  output_dir: "stanza" # /path/to/output/dir
  label: "Nikkaji entry"
  definition: "Name and Chemical formula for Nikkaji Entry"
  sparql: sparql  # defined in sparql.yaml
  parameters:
    nikkaji_number:
      example: "J2.330B"
      description: Nikkaji number
      required: true
