gm: <http://togomedium.org/>
gmo: <http://purl.jp/bio/10/gmo/>
dcterms: <http://purl.org/dc/terms/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
xsd: <http://www.w3.org/2001/XMLSchema#>
skos: <http://www.w3.org/2004/02/skos/core#>
obo: <http://purl.obolibrary.org/obo/>
olo: <http://purl.org/ontology/olo/core#>
sio: <http://semanticscience.org/resource/>
