title: PubCaseFinder RDF
website: https://pubcasefinder.dbcls.jp/
description: PubCaseFinder (PCF) is a Human Phenotype Ontology (HPO)-based clinical decision support system for rare and genetic diseases, always up-to-date.
tags: [ Rare Disease, Genetic Disease, Human Phenotype Ontology, Phenotype, Disease Search ]
provider: Database Center for Life Science
creators:
  - name: Jaemoon Shin
    affiliation: Database Center for Life Science
  - name: Atsuko Yamaguchi
    affiliation: Database Center for Life Science
  - name: Shuichi Kawashima
    affiliation: Database Center for Life Science
  - name: Toyofumi Fujiwara
    affiliation: Database Center for Life Science
version: 1.3.0
issued: 2021-05-18
licenses:
  - Attribution 4.0 International (CC BY 4.0) Database Center for Life Science
