- PubCaseFinder mim:103580:
    - a:
        - ncit:C7057
        - med2rdf:Disease
    - nando:hasInheritance*:
        - obo:HP_0000006 # Autosomal dominant inheritance
    - dct:identifier:
        - xsd:string: "103580"
    - rdfs:label:
        - label_ja: '"偽性副甲状腺機能低下症 Ia 型 (PHP IA)"@ja'
    - dct:identifier:
        - nando_id: "1200004"
    - rdfs:seeAlso+:
        - see_also: <http://purl.obolibrary.org/obo/MONDO_0007078> # pseudohypoparathyroidism type 1A
        - see_also: <>
