dcterms: <http://purl.org/dc/terms/>
bibo: <http://purl.org/ontology/bibo/>
fabio: <http://purl.org/spar/fabio>
foaf: <http://xmlns.com/foaf/0.1>
hgnc: <https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/>
ihp: <http://identifiers.org/>
ipubmed: <http://identifiers.org/pubmed/>
nando: <http://nanbyodata.jp/ontology/nando#>
ncbigene: <http://identifiers.org/ncbigene/>
ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
med2rdf: <http://med2rdf.org/ontology/>
mesh: <http://id.nlm.nih.gov/mesh/>
mim: <http://identifiers.org/mim/>
oa: <http://www.w3.org/ns/oa#>
obo: <http://purl.obolibrary.org/obo/>
ordo: <http://www.orpha.net/ORDO/>
pubmed: <http://rdf.ncbi.nlm.nih.gov/pubmed/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
sio: <http://semanticscience.org/resource/>
nuc: <http://ddbj.nig.ac.jp/ontologies/nucleotide/>
hop: <http://purl.org/net/orthordf/hOP/ontology#>
hoom: <http://www.semanticweb.org/ontology/HOOM>