title: NCBI Gene RDF
website: https://www.ncbi.nlm.nih.gov/gene/
description: NCBI Gene RDFは、NCBI GeneのデータをRDFに変換したものです。
tags: [Gene]
provider: National Center for Biotechnology Information
creators:
  - name: 千葉 啓和
    affiliation: ライフサイエンス統合データベースセンター
version: release_20230525
issued: 2022-05-25
licenses:
  - https://www.ncbi.nlm.nih.gov/home/about/policies/
