title: NCBI Gene RDF
website: https://www.ncbi.nlm.nih.gov/gene/
description: NCBI Gene RDF is a translation of NCBI Gene data into RDF.
tags: [Gene]
provider: National Center for Biotechnology Information
creators:
  - name: Hirokazu Chiba
    affiliation: Database Center for Life Science
version: release_20230525
issued: 2022-05-25
licenses:
  - https://www.ncbi.nlm.nih.gov/home/about/policies/
