- Gene ncbigene:34:
  - a: insdc:Gene
  - dct:identifier:
    - id: 34
  - rdfs:label:
    - label: "ACADM"
  - insdc:standard_name?:
    - standard_name: "ACADM"
  - insdc:locus_tag?:
    - locus_tag: ""
  - insdc:gene_synonym*:
    - gene_synonym: "ACAD1"
  - dct:description?:
    - gene_description: "acyl-CoA dehydrogenase medium chain"
  - dct:alternative*:
    - alternative: "medium-chain specific acyl-CoA dehydrogenase, mitochondrial"
  - insdc:dblink*:
    - dblink: hgnc:89
  - insdc:db_xref*:
    - db_xref: "AllianceGenome:HGNC:89"
  - ncbio:typeOfGene:
    - type_of_gene: "protein-coding"
  - ncbio:nomenclatureStatus?:
    - nomenclature_status: "official"
  - ncbio:fullName?:
    - full_name: "acyl-CoA dehydrogenase medium chain"
  - ncbio:featureType*:
    - feature_type: ""
  - ncbio:taxid:
    - taxid: taxid:9606
  - insdc:chromosome?:
    - chromosome: "1"
  - insdc:map?:
    - map: "1p31.1"
  - dct:modified:
    - modified: "2021-02-07"
