rdfs: <http://www.w3.org/2000/01/rdf-schema#>
dct: <http://purl.org/dc/terms/>
xsd: <http://www.w3.org/2001/XMLSchema#>
ncbigene: <http://identifiers.org/ncbigene/>
taxid: <http://identifiers.org/taxonomy/>
hgnc: <http://identifiers.org/hgnc/>
mim: <http://identifiers.org/mim/>
mirbase: <http://identifiers.org/mirbase/>
ensembl: <http://identifiers.org/ensembl/>
insdc: <http://ddbj.nig.ac.jp/ontologies/nucleotide/>
ncbio: <https://dbcls.github.io/ncbigene-rdf/ontology.ttl#>
