 title: Quanto RDF
 website: https://sra.dbcls.jp/
 description: Raw sequence data quality statistics calculated from the Sequence Read Archive data
 tags: []
 provider:
 creators:
   - name: Tazro Inutano Ohta
     affiliation: Database Center for Life Science
   - name: Name 2
     affiliation: Affiliation 2
 version: 	0.1.2
 issued: 	2016-07-12
 licenses:
   - Attribution 4.0 International (CC BY 4.0)
