cc4: <http://creativecommons.org/licenses/by-sa/4.0/>
dbcls: <http://dbcls.rois.ac.jp/>
sra: <http://identifiers.org/insdc.sra/>
sos: <http://purl.jp/bio/01/quanto/ontology/sos#>
quanto: <http://purl.jp/bio/01/quanto/resource/>
pav: <http://purl.org/pav/>
obo: <http://purl.obolibrary.org/obo/>
dct: <http://purl.org/dc/terms/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
foaf: <http://xmlns.com/foaf/0.1/>
