title: DBKERO RDF
website: http://kero.hgc.jp/rdf/
description: DBKERO is a collection of multi-omics data sets including SNV, RNA-seq, ChIP-seq, BS-seq and TSS-seq. The ChIP-seq part is big, so its lite version chip_seq_lite is included. The original big ChIP-seq data can also be downloaded at https://integbio.jp/rdf/download/kero/2017-01-27/all/chip_seq_all.tar.gz .
tags: [Genome, Polymorphism, Other DNA, Gene expression, Others]
provider:
creators:
  - name: Shin Kawano
    affiliation: Database Center for Life Science
  - name: Hiroyuki Wakaguri
    affiliation: Graduate School of Frontier Sciences, The University of Tokyo
  - name: Yutaka Suzuki
    affiliation: Graduate School of Frontier Sciences, The University of Tokyo
version: 2017-01-27
issued: 2017-01-27
licenses:
  - Attribution 4.0 International (CC BY 4.0) 
