kero: <http://kero.hgc.jp/ontology/kero.owl#>
bsseqdata: <http://kero.hgc.jp/rdf/data/9/BSseq/>
bsseqdataset: <http://kero.hgc.jp/rdf/dataset/9/BSseq/>
chipseqdata: <http://kero.hgc.jp/rdf/data/9/ChIPseq/>
chipseqdataset: <http://kero.hgc.jp/rdf/dataset/9/ChIPseq/>
chromhmmdata: <http://kero.hgc.jp/rdf/data/9/ChromHMM/>
chromhmmdataset: <http://kero.hgc.jp/rdf/dataset/9/ChromHMM/>
rnaseqdata: <http://kero.hgc.jp/rdf/data/9/RNAseq/>
rnaseqdataset: <http://kero.hgc.jp/rdf/dataset/9/RNAseq/>
snvdata: <http://kero.hgc.jp/rdf/data/9/SNV/>
snvdataset: <http://kero.hgc.jp/rdf/dataset/9/SNV/>
tssseqdata: <http://kero.hgc.jp/rdf/data/9/TSSseq/>
tssseqdataset: <http://kero.hgc.jp/rdf/dataset/9/TSSseq/>
sample: <http://kero.hgc.jp/rdf/sample/>
species: <http://kero.hgc.jp/rdf/species/>
taxonomy: <http://identifiers.org/taxonomy/>
hg38: <http://kero.hgc.jp/rdf/resource/homo_sapiens/hg38/>
grch38: <http://rdf.ebi.ac.uk/resource/ensembl/homo_sapiens/GRCh38/>
ncbigene: <http://identifiers.org/ncbigene/>
refseq: <http://identifiers.org/refseq/>
dbsnp: <http://identifiers.org/dbsnp/>
dct: <http://purl.org/dc/terms/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
dcat: <http://www.w3.org/ns/dcat#>
efo: <http://www.ebi.ac.uk/efo/>
obo: <http://purl.obolibrary.org/obo/>
dct: <http://purl.org/dc/terms/>
sio: <http://semanticscience.org/resource/>
foaf: <http://xmlns.com/foaf/0.1/>
skos: <http://www.w3.org/2004/02/skos/core#>
dbpedia: <http://dbpedia.org/ontology/>
snomedct: <http://purl.bioontology.org/ontology/SNOMEDCT/>
faldo: <http://biohackathon.org/resource/faldo#>
ensemblevariation: <http://rdf.ebi.ac.uk/terms/ensemblvariation#>
