# Cardinality is yet to be fixed.
- Class ncit:C1000:
  - a: owl:Class
  - ncit:NHC0:  # code
    - id: "C1000"
  - rdfs:label:
    - label: "Recombinant Amphiregulin"
  - ncit:A1*:  # Role_Has_Domain
    - role_has_domain: Class
  - ncit:A2*:  # Role_Has_Range
    - role_has_range: Class
  - ncit:A3*:  # Role_Has_Parent
    - role_has_parent: Class
  - ncit:A4*:  # Qualifier_Applies_To
    - qualifier_applies_to: Class
  - ncit:A5*:  # Has_Salt_Form
    - has_salt_form: Class
  - ncit:A6*:  # Has_Free_Acid_Or_Base_Form
    - has_free_acid_or_base_form: Class
  - ncit:A7*:  # Has_Target
    - has_target: Class
  - ncit:A8*:  # Concept_In_Subset
    - concept_in_subset: Class
  - ncit:A9*:  # Is_Related_To_Endogenous_Product
    - is_related_to_endogenous_product: Class
  - ncit:A12*:  # Has_Data_Element
    - has_data_element: Class
  - ncit:A13*:  # Related_To_Genetic_Biomarker
    - related_to_genetic_biomarker: Class
  - ncit:A14*:  # Neoplasm_Has_Special_Category
    - neoplasm_has_special_category: Class
  - ncit:A15*:  # Has_CTCAE_5_Parent
    - has_ctcae_5_parent: Class
  - ncit:A16*:  # Has_INC_Parent
    - has_inc_parent: Class
  - ncit:A17*:  # Has_Pharmaceutical_State_Of_Matter
    - has_pharmaceutical_state_of_matter: Class
  - ncit:A18*:  # Has_Pharmaceutical_Basic_Dose_Form
    - has_pharmaceutical_basic_dose_form: Class
  - ncit:A19*:  # Has_Pharmaceutical_Administration_Method
    - has_pharmaceutical_administration_method: Class
  - ncit:A20*:  # Has_Pharmaceutical_Intended_Site
    - has_pharmaceutical_intended_site: Class
  - ncit:A21*:  # Has_Pharmaceutical_Release_Characteristics
    - has_pharmaceutical_release_characteristics: Class
  - ncit:A22*:  # Has_Pharmaceutical_Transformation
    - has_pharmaceutical_transformation: Class
  - ncit:A23*:  # Has_PCDC_Data_Type
    - has_pcdc_data_type: Class
  - ncit:A24*:  # Is_PCDC_AML_Authorized_Value_For_Variable
    - is_pcdc_aml_authorized_value_for_variable: Class
  - ncit:A25*:  # Value_Set_Is_Paired_With
    - value_set_is_paired_with: Class
  - ncit:A26*:  # Has_PCDC_AML_Authorized_Value
    - has_pcdc_aml_authorized_value: Class
  - ncit:A27*:  # Has_CTDC_Value
    - has_ctdc_value: Class
  - ncit:A28*:  # Is_PCDC_EWS_Authorized_Value_For_Variable
    - is_pcdc_ews_authorized_value_for_variable: Class
  - ncit:A29*:  # Has_PCDC_EWS_Authorized_Value
    - has_pcdc_ews_authorized_value: Class
  - ncit:A30*:  # Has_ICDC_Value
    - has_icdc_value: Class
  - ncit:A31*:  # Has_GDC_Value
    - has_gdc_value: Class
  - ncit:A32*:  # Is_Value_For_GDC_Property
    - is_value_for_gdc_property: Class
  - ncit:A33*:  # Is_PCDC_GCT_Authorized_Value_For_Variable
    - is_pcdc_gct_authorized_value_for_variable: Class
  - ncit:A34*:  # Has_PCDC_GCT_Authorized_Value
    - has_pcdc_gct_authorized_value: Class
  - ncit:A35*:  # Is_PCDC_ALL_Authorized_Value_For_Variable
    - is_pcdc_all_authorized_value_for_variable: Class
  - ncit:A36*:  # Has_PCDC_ALL_Authorized_Value
    - has_pcdc_all_authorized_value: Class
  - ncit:A37*:  # Has_SeroNet_Authorized_Value
    - has_seronet_authorized_value: Class
  - ncit:A38*:  # Has_PCDC_OS_Authorized_Value
    - has_pcdc_os_authorized_value: Class
  - ncit:A39*:  # Has_PCDC_HL_Authorized_Value
    - has_pcdc_hl_authorized_value: Class
  - ncit:A40*:  # Has_DIPG_DMG_Authorized_Value
    - has_dipg_dmg_authorized_value: Class
  - ncit:A42*:  # Has_OORO_PC_Value
    - has_ooro_pc_value: Class
  - ncit:A48*:  # Has_ACC-AHA_SARS2_Authorized_Value
    - has_acc_aha_sars2_authorized_value: Class
  - ncit:P100*:  # OMIM_Number
    - omim_number: "100640"
  - ncit:P101*:  # Homologous_Gene
    - homologous_gene: "14-3-3 Family"
  - ncit:P102*:  # GenBank_Accession_Number
    - genbank_accession_number: "A64377"
  - ncit:P106*:  # Semantic_Type
    - semantic_type: "Amino Acid, Peptide, or Protein"
  - ncit:P107*:  # Display_Name
    - display_name: "1,2-Carbon C 13-labeled Glucose"
  - ncit:P108*:  # Preferred_Name
    - preferred_name: "(E3-Independent) E2 Ubiquitin-Conjugating Enzyme"
  - ncit:P167*:  # Image_Link
    - image_link: "http://ccm.ucdavis.edu/cfsidserver/view.cfm?cat=Mouse_N_Prostate&img=MP19.sid&rgn=&nlvl=5&iwid=26150&ihei=27998"
  - ncit:P171*:  # PubMedID_Primary_Reference
    - pubmedid_primary_reference: "10022751"
  - ncit:P175*:  # NSC Number
    - nsc_number: "10004"
  - ncit:P200*:  # OLD_PARENT
    - old_parent: "101 Mouse"
  - ncit:P201*:  # OLD_CHILD
    - old_child: "AA_Mouse"
  - ncit:P203*:  # OLD_KIND
    - old_kind: "Abnormal_Cell_Kind"
  - ncit:P204*:  # OLD_ROLE
    - old_role: "Anatomic_Structure_Is_Physical_Part_Of some Kidney"
  - ncit:P205*:  # OLD_STATE
    - old_state: "Defined"
  - ncit:P207*:  # UMLS_CUI
    - umls_cui: "C0000248"
  - ncit:P208*:  # NCI_META_CUI
    - nci_meta_cui: "CL000384"
  - ncit:P210*:  # CAS_Registry
    - cas_registry: "100-33-4"
  - ncit:P211*:  # GO_Annotation
    - go_annotation: "cytoplasm"
  - ncit:P215*:  # KEGG_ID
    - kegg_id: "hsa00010"
  - ncit:P216*:  # BioCarta_ID
    - biocarta_id: "Cysteine2Pathway"
  - ncit:P302*:  # Accepted_Therapeutic_Use_For
    - accepted_therapeutic_use_for: "Acute Coronary Syndrome"
  - ncit:P310*:  # Concept_Status
    - concept_status: "Header_Concept"
  - ncit:P315*:  # SNP_ID
    - snp_id: "rs10079250"
  - ncit:P316*:  # Relative_Enzyme_Activity
    - relative_enzyme_activity: "0"
  - ncit:P317*:  # FDA_Table
    - fda_table: "Device Problem Code (Appendix B)"
  - ncit:P319*:  # FDA_UNII_Code
    - fda_unii_code: "000705ZASD"
  - ncit:P320*:  # OID
    - oid: "2.16.840.1.113883.3.26.1.1"
  - ncit:P321*:  # EntrezGene_ID
    - entrezgene_id: "10"
  - ncit:P322*:  # Contributing_Source
    - contributing_source: "ACC"
  - ncit:P325*:  # ALT_DEFINITION
    - alt_definition: "0 to 24 hours after stent implantation. (Cutlip DE, Windecker S, Mehran R, et al. Clinical Endpoints in Coronary Stent Trials : A Case for Standardized Definitions. Circulation. 2007;115:2344-2351)"
  - ncit:P329*:  # PDQ_Open_Trial_Search_ID
    - pdq_open_trial_search_id: "256405"
  - ncit:P330*:  # PDQ_Closed_Trial_Search_ID
    - pdq_closed_trial_search_id: "256405"
  - ncit:P331*:  # NCBI_Taxon_ID
    - ncbi_taxon_id: "1000425"
  - ncit:P332*:  # MGI_Accession_ID
    - mgi_accession_id: "MGI:2159737"
  - ncit:P333*:  # Use_For
    - use_for: "Accuracy rate"
  - ncit:P334*:  # ICD-O-3_Code
    - icd_o_3_code: "0000/0"
  - ncit:P350*:  # Chemical_Formula
    - chemical_formula: "(C2H4)n"
  - ncit:P351*:  # US_Recommended_Intake
    - us_recommended_intake: "Y"
  - ncit:P352*:  # Tolerable_Level
    - tolerable_level: "Y"
  - ncit:P353*:  # INFOODS
    - infoods: "AL"
  - ncit:P354*:  # USDA_ID
    - usda_id: "203"
  - ncit:P355*:  # Unit
    - unit: "Calorie"
  - ncit:P356*:  # Essential_Amino_Acid
    - essential_amino_acid: "Y"
  - ncit:P357*:  # Essential_Fatty_Acid
    - essential_fatty_acid: "Y"
  - ncit:P358*:  # Nutrient
    - nutrient: "Y"
  - ncit:P359*:  # Micronutrient
    - micronutrient: "Y"
  - ncit:P360*:  # Macronutrient
    - macronutrient: "Y"
  - ncit:P361*:  # Extensible_List
    - extensible_list: "Yes"
  - ncit:P362*:  # miRBase_ID
    - mirbase_id: "MI0000060"
  - ncit:P363*:  # Neoplastic_Status
    - neoplastic_status: "Benign"
  - ncit:P364*:  # OLD_ASSOCIATION
    - old_association: "'Alvespimycin Hydrochloride'"
  - ncit:P365*:  # OLD_SOURCE_ASSOCIATION
    - old_source_association: "A8|C101445"
  - ncit:P366*:  # Legacy Concept Name
    - legacy_concept_name: "A-007"
  - ncit:P367*:  # PID_ID
    - pid_id: "a4b1_a4b7_pathway"
  - ncit:P368*:  # CHEBI_ID
    - chebi_id: "CHEBI:10003"
  - ncit:P369*:  # HGNC_ID
    - hgnc_id: "HGNC:1000"
  - ncit:P371*:  # NICHD_Hierarchy_Term
    - nichd_hierarchy_term: "Spondylitis"
  - ncit:P372*:  # Publish_Value_Set
    - publish_value_set: "Yes"
  - ncit:P375*:  # Maps_To
    - maps_to: "Human Tumor Original Cells"
  - ncit:P376*:  # Term_Browser_Value_Set_Description
    - term_browser_value_set_description: "<p> Terminology that includes terms pertaining to FDA/USP Substance Registration System (SRS), which is to support health information technology initiatives by generating unique ingredient identifiers (UNIIs) for substances in drugs, biologics, foods, and devices. </p><p> UNII Terminology can be downloaded from this location <a href=\"https://evs.nci.nih.gov/ftp1/FDA/UNII\">FDA UNII</a>.</p>"
  - ncit:P398*:  # Value_Set_Pair
    - value_set_pair: "Yes"
  - ncit:P399*:  # NCI_Drug_Dictionary_ID
    - nci_drug_dictionary_id: "256405"
  - ncit:P400*:  # ClinVar_Variation_ID
    - clinvar_variation_id: "1000203"
  - ncit:P90*:  # FULL_SYN
    - full_syn: "AAT"
  - ncit:P92*:  # Subsource
    - subsource: "ICD"
  - ncit:P93*:  # Swiss_Prot
    - swiss_prot: "A0A0B4J1V1"
  - ncit:P96*:  # Gene_Encodes_Product
    - gene_encodes_product: "ABL-Interactor 2"
  - ncit:P97*:  # DEFINITION
    - definition: "0 to 24 hours after stent implantation. (Cutlip DE, Windecker S, Mehran R, et al. Clinical Endpoints in Coronary Stent Trials : A Case for Standardized Definitions. Circulation. 2007;115:2344-2351)"
  - ncit:P98*:  # DesignNote
    - designnote: "A stable complex of MCM4, MCM6, and MCM7 associates with MCM2 specifically bound to histone H3. A key component of the pre-replication complex, hexameric MCM2-7 complex is likely involved in formation of replication forks and recruitment of replication factors. MCM2/4/6/7 complex possesses ATP-dependent DNA helicase activity and may initiate replication as a DNA unwinding enzyme. MCM4 phosphorylation by Cyclin/CDK1,2 suppresses helicase activity and chromatin binding, regulating replication. MCM4 is highly phosphorylated in mitotic cells"
  - oboinowl:hasDbXref*:
    - xref: "IMDRF:E0128"
  - owl:disjointWith*:
    - disjointwith: Class
  - owl:equivalentClass*:
    - equivalentclass: Class
  # - owl:complementOf*:
  #   - complementof: 
  # - owl:intersectionOf*:
  #   - intersectionof: 
  # - owl:unionOf*:
  #   - unionof: 

