xml: <http://www.w3.org/XML/1998/namespace/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
xsd: <http://www.w3.org/2001/XMLSchema#>
obo: <http://purl.obolibrary.org/obo/>
owl: <http://www.w3.org/2002/07/owl#>
skos: <http://www.w3.org/2004/02/skos/core#>
#chebi: <http://purl.obolibrary.org/obo/chebi#>
obochebi_sha: <http://purl.obolibrary.org/obo/chebi#>
obochebi: <http://purl.obolibrary.org/obo/chebi/>
#      chebi1: <http://purl.obolibrary.org/obo/chebi/>
#obochebi_dot: <http://purl.obolibrary.org/obo/chebi.>
#metadata: <http://data.bioontology.org/metadata/>
#oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
oboinowl: <http://www.geneontology.org/formats/oboInOwl#>